### ISSUE TITLE
Program crashes when it reaches the end of a video

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#11]
If I hold down the 'd' or 's' key until the program reaches the end of the video, it crashes with the following error:

Traceback (most recent call last):
  File "mainV2.py", line 163, in <module>
    main(sys.argv[1:])
  File "mainV2.py", line 104, in main
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Derek-Lun** [comment]
See if it is still reproducible

**Comment by pcernek** [comment]
push first? :grinning:

**Comment by Derek-Lun** [comment]
should be pushed

**Comment by Derek-Lun** [comment]
fixed!
