### ISSUE TITLE
Weird 'E' in label file when I go back to frame designated as empty

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#12]
Steps to reproduce:
1. press 'n' to label frame as empty. This takes you to next frame.
2. press 'a' to go back to the frame just labeled as empty.
3. press 'esc' to write to file.

Label file contains " ('E',) " as a label for the frame that was supposed to be empty.

This does not happen if I press 'n' again after going back to the frame previously labeled as empty.

**Comment by Derek-Lun** [comment]
fixed!
