### ISSUE TITLE
Output meta-info file

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#5]
Maybe we want to adopt the convention of always outputting these meta-info files in the same directory as the video file that was used to generate them. Maybe we also want to assume that all our video files are in the same directory, each with a unique name. Then we can just name the meta-info files as "<video_name>.labels", where <video_name> is the name of the video file before the file extension.

I'm open to further suggestions on this topic.

**Comment by pcernek** [comment]
I've shared a sample output file with you on Slack.

**Comment by Derek-Lun** [comment]
done!

**Comment by pcernek** [comment]
Nice!! This turned out to be a super effective way to collaborate, wouldn't you say?
