### ISSUE TITLE
Platform dependency of waitkey()

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#6]
One of the lower answers on [this page](http://stackoverflow.com/questions/14494101/using-other-keys-for-the-waitkey-function-of-opencv) confirms that the int returned by cv2.waitkey() is platform dependent, except for the LSB.

I suggest [this workaround](http://choorucode.com/2015/01/20/how-to-use-opencv-waitkey-in-python/), it works on my machine (note that by casting the return value of waitkey to char there is no need to then compare it to e.g. ord('c'), you can simply compare it to 'c')

**Comment by pcernek** [comment]
By the same token, it might be easier to avoid using the arrow keys, since I'm not sure these map neatly onto ASCII. which the workaround posted above relies upon.

Suggested key mapping (all from the left hand while the right hand clicks the mouse):

d = "next"
a = "previous"
w = "skip (25 frames ahead)"
s = "skip (25 frames back)"
spacebar = "empty frame" (no ROI)
r = "record" (save the currently selected ROIs)
z = "uncertain"

...but do with these as you will.

**Comment by pcernek** [comment]
I think you solved this one, no?

**Comment by Derek-Lun** [comment]
the current control scheme is the following:

d = "next"
a = "previous"
w = "skip (24 frames back)"
s = "skip (24 frames ahead)"
n = "empty"
z = "uncertain"
esc = "quit"
