### ISSUE TITLE
Size of paintbrush is off by 1

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#7]
To reproduce bug:
-when program is first started, brush size is 1 pixel. Good.
-press '2' key. brush size is now 5x5.
-press '1' key. brush size is now 3x3. No way to get back to 1px brush.

**Comment by Derek-Lun** [comment]
press '0' key for 1px

**Comment by pcernek** [comment]
oh right. I hope you don't mind if I subtract 1 from the num_key_lookup function to make it more intuitive :smile:

**Comment by Derek-Lun** [comment]
done
