### ISSUE TITLE
Make highlighted pixels persist across frames

### ISSUE THREAD

**Issue by pcernek** [Derek-Lun/UBCSailBot-VideoTrainingData#9]
Right now, when I select pixels on a frame, then go to a different frame, then come back again, the pixels that I selected on the initial frame are no longer visible (though they are still written to the output file).

If it's not too difficult to implement, it would be good to have previously-selected pixels be displayed again  when going back to a previously-labelled frame.

**Comment by Derek-Lun** [comment]
done!
